#include "ppm_file.hh"

/*
** PPM PIXEL
*/

PpmPixel::PpmPixel(std::uint32_t red, std::uint32_t green, std::uint32_t blue)
    : red_(red)
    , green_(green)
    , blue_(blue)
{}

std::uint32_t PpmPixel::getRed() const
{
    return red_;
}

std::uint32_t PpmPixel::getGreen() const
{
    return green_;
}

std::uint32_t PpmPixel::getBlue() const
{
    return blue_;
}

/*
** PPM FILE
*/

PpmFile::PpmFile()
    : width_(0)
    , height_(0)
    , max_value_(0)
{}

PpmFile::PpmFile(std::uint32_t width, std::uint32_t height,
    std::uint32_t max_value)
    : width_(width)
    , height_(height)
    , max_value_(max_value)
{}

void PpmFile::skipCommentaries(std::ifstream& file, std::string& line)
{
    while (std::getline(file, line) && line.starts_with('#'))
    {}
}

PpmFile* PpmFile::makeFile(std::filesystem::path path)
{
    std::ifstream file(path, std::ios::binary);
    if (!file.is_open())
    {
        throw std::runtime_error("Could not open ppm file: " + path.string());
    }

    PpmFile* ppm_file = new PpmFile();

    // We check the header
    std::string line;
    std::getline(file, line);
    if (line != "P3")
    {
        file.close();
        delete ppm_file;
        return nullptr;
    }

    // We skip the commentary, whether it is the commentary generated by Gimp
    // or the one generated by ObsCureFileParser
    // TODO: it's not good to assume there is only one comment, but since the
    // ppm files are going to be generated by this program, or modified on
    // (hopefully) Gimp, it shouldn't be a big issue
    std::getline(file, line);
    std::uint32_t width;
    file >> width;
    ppm_file->setWidth(width);

    std::uint32_t height;
    file >> height;
    ppm_file->setHeight(height);

    std::uint32_t max_value;
    file >> max_value;
    ppm_file->setMaxValue(max_value);

    // We read the main content
    // Hmm maybe I should have a counter and just check at which state we are
    // instead of trying to read the 3 colours in the same loop
    int counter = 0;
    std::uint32_t red;
    std::uint32_t green;
    std::uint32_t blue;
    while (file)
    {
        switch (counter)
        {
        case 0: // red
            file >> red;
            break;
        case 1: // green
            file >> green;
            break;
        case 2: // blue
            file >> blue;
            ppm_file->pixels_.push_back(PpmPixel(red, green, blue));
            break;
        }

        counter++;
        if (counter > 2)
        {
            counter = 0;
        }
    }

    if (ppm_file->pixels_.size() != width * height)
    {
        file.close();
        delete ppm_file;
        return nullptr;
    }

    file.close();
    return ppm_file;
}

void PpmFile::serialize(std::filesystem::path path)
{
    std::ofstream file(path, std::ios::binary);

    file << "P3" << std::endl;
    file << "# Created by ObsCureFileParser" << std::endl;
    file << width_ << " " << height_ << std::endl;
    file << max_value_ << std::endl;

    for (PpmPixel& pixel : pixels_)
    {
        file << pixel.getRed() << std::endl;
        file << pixel.getGreen() << std::endl;
        file << pixel.getBlue() << std::endl;
    }

    file.close();
}

std::uint32_t PpmFile::getWidth() const
{
    return width_;
}

std::uint32_t PpmFile::getHeight() const
{
    return height_;
}

std::uint32_t PpmFile::getMaxValue() const
{
    return max_value_;
}

std::vector<PpmPixel>& PpmFile::getPixels()
{
    return pixels_;
}

void PpmFile::setWidth(std::uint32_t width)
{
    width_ = width;
}

void PpmFile::setHeight(std::uint32_t height)
{
    height_ = height;
}

void PpmFile::setMaxValue(std::uint32_t max_value)
{
    max_value_ = max_value;
}